import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, Rating } from "flowbite-react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center items-center h-screen flex-col gap-6">
          <div>
            <div className="flex flex-wrap gap-2">
              <div>
                <Button>Default</Button>
              </div>
              <div>
                <Button color="gray">Gray</Button>
              </div>
              <div>
                <Button color="dark">Dark</Button>
              </div>
              <div>
                <Button color="light">Light</Button>
              </div>
              <div>
                <Button color="success">Success</Button>
              </div>
              <div>
                <Button color="failure">Failure</Button>
              </div>
              <div>
                <Button color="warning">Warning</Button>
              </div>
              <div>
                <Button color="purple">Purple</Button>
              </div>
            </div>
          </div>
          <div className="">
            <Rating>
              <Rating.Star />
              <Rating.Star />
              <Rating.Star />
              <Rating.Star />
              <Rating.Star filled={false} />
              <p className="ml-2 text-sm font-medium text-gray-500 dark:text-gray-400">
                4.95 out of 5
              </p>
            </Rating>
          </div>
        </div>
      </main>
    </>
  );
}
